m-nath/golfriend

app/assets/stylesheets/config/_colors.scss

color updated
@m-nath please have a check

added new color

---

Gemfile
Gemfile.lock
app/models/event.rb
app/models/reservation.rb
db/migrate/20190814010000_create_events.rb
db/migrate/20190814022831_create_reservations.rb
db/schema.rb
db/seeds.rb
test/models/event_test.rb
test/models/reservation_test.rb

@m-nath boss pls check.
@HuishuJia @sho-hei-sd 
created 2 models, and seeds

created 2 models, and seeds

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_fonts.scss

changed font

---

app/controllers/reservations_controller.rb
app/models/event.rb
app/models/reservation.rb
app/models/user.rb
config/routes.rb
db/migrate/20190814022831_create_reservations.rb
db/schema.rb
db/seeds.rb
test/controllers/reservations_controller_test.rb

made routes

---

app/controllers/events_controller.rb
app/views/events/index.html.erb
app/views/events/new.html.erb
app/views/events/show.html.erb
test/controllers/events_controller_test.rb

@m-nath pls check
@HuishuJia @sho-hei-sd  please pull

done events controller (CRUD)

---

app/controllers/reservations_controller.rb
app/controllers/users_controller.rb
test/controllers/users_controller_test.rb

added reservation and user  controllers

add reservation and user controllers

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/events_controller.rb
app/policies/application_policy.rb
app/policies/event_policy.rb
db/migrate/20190814075747_add_admin_to_users.rb
db/schema.rb
db/seeds.rb
test/policies/event_policy_test.rb

@m-nath 
@sho-hei-sd @HuishuJia

done pundit for events

---

app/views/pages/home.html.erb

double checked the banner

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search_bar.scss
app/assets/stylesheets/config/_fonts.scss
app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
db/seeds.rb

@m-nath 
@sho-hei-sd @HuishuJia

edited homepage, connect to events controller and seeds

---

app/assets/stylesheets/components/_card.scss
app/controllers/pages_controller.rb
app/views/pages/home.html.erb

pls check
@m-nath 
@sho-hei-sd  @HuishuJia

changed card css grid,page home controller sample number

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_event_description.scss
app/assets/stylesheets/components/_single_event_card.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/events/show.html.erb
app/views/layouts/application.html.erb

- show page 80% done;
- update application html head 'website name'

Show page 80% done

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/events/edit.html.erb

sign-up
log-in
new
edit.....
all the forms that I can think of are done

I think all the form is done

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/events_controller.rb
app/models/event.rb
app/views/events/index.html.erb

@m-nath pls merge
@sho-hei-sd  @HuishuJia

search bar done

---

app/assets/stylesheets/components/_navbar.scss

made a space among nav items("Add an event", "My Events", "avatar")

made a space between nav items

---

app/assets/stylesheets/components/_find_event_card.scss
app/views/events/index.html.erb

changed the height in find-event card

changed the height of the find-event card

---

app/views/pages/home.html.erb
db/schema.rb

changed the position of container to center

changed the container position to center

---

app/assets/stylesheets/components/_banner.scss
app/views/pages/home.html.erb

changed the position of banner a bit

changed vh in _banner.scss

---

app/views/shared/_navbar.html.erb

added nav item which is All events.
added link to it as well.

added navitem called  All events

---

app/assets/stylesheets/components/_button.scss
app/views/pages/home.html.erb

added All-events button

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_find_event_card.scss
app/views/events/index.html.erb
app/views/pages/home.html.erb

added button in left event-card

added button in event-card

---

app/assets/stylesheets/components/_card.scss
app/views/pages/home.html.erb

Home change avatar

---

app/views/pages/home.html.erb

put correct link path on the button of My-event

put correct link path on the button of My-event

---

app/views/pages/home.html.erb

changed the letters to My events on button.

changed the letters to event-card-buttonn

---

app/views/events/show.html.erb

back-end fix that we did together.
Tomorrow continue the front-end!

just started, continue tomorrow

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_find_event_card.scss
app/views/pages/home.html.erb

changed the button positioning

changed the positions of buttons

---

app/views/pages/home.html.erb

Not only container position but also search bar position.

set container to correct position AND SEARCH BAR as well

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

made change on letter of "Log-in"

changed the color of login

---

app/assets/stylesheets/components/_find_event_card.scss
app/views/pages/home.html.erb
db/schema.rb

change letter of size bigger in find-cards

---

app/views/shared/_navbar.html.erb

deleted add-event in nav bar

---

app/views/shared/_navbar.html.erb

deleted the name of accoutn

---

app/views/events/new.html.erb
db/schema.rb

changed the position of container in CREATE page.

changed the position of container

---

app/views/pages/home.html.erb

delete search bar and make map bigger

---

app/views/shared/_navbar.html.erb

deleted fas search icon
